plugins { id 'java' }

group = 'me.ehsan'
version = '0.1.0-SNAPSHOT'

repositories {
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://repo.extendedclip.com/content/repositories/placeholderapi/' }
    maven { url = 'https://repo.luckperms.net/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly 'net.luckperms:api:5.4'
    compileOnly 'me.clip:placeholderapi:2.11.6'
}

java { toolchain.languageVersion = JavaLanguageVersion.of(21) }

processResources {
    filesMatching('plugin.yml') { expand(version: project.version) }
}

jar { archiveBaseName = 'ThunderChat' }
