package me.ehsan.thunderchat.network;

import me.ehsan.thunderchat.ThunderChat;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.plugin.messaging.PluginMessageListener;
import java.io.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/** Single ThunderChat network transport/dispatcher for BungeeCord-compatible forwarding. */
public final class NetworkMessenger implements PluginMessageListener {
    private static final String CHANNEL="BungeeCord"; private static final String SUBCHANNEL="ThunderChat"; private final ThunderChat plugin;
    private final Map<UUID,Long> seenPackets=new ConcurrentHashMap<>();
    public NetworkMessenger(ThunderChat plugin){this.plugin=plugin;plugin.getServer().getMessenger().registerOutgoingPluginChannel(plugin,CHANNEL);plugin.getServer().getMessenger().registerIncomingPluginChannel(plugin,CHANNEL,this);plugin.getServer().getScheduler().runTaskTimerAsynchronously(plugin,()->{long cutoff=System.currentTimeMillis()-120_000;seenPackets.entrySet().removeIf(e->e.getValue()<cutoff);},2400L,2400L);}
    public void forwardAll(Player carrier,byte[] payload)throws IOException{if(!plugin.getPluginConfig().getBoolean("network.enabled",true))return;if(payload==null||payload.length>65500)throw new IOException("Invalid ThunderChat network payload");if(carrier==null)throw new IOException("No connected player carrier is available");byte[] envelope=wrap(payload);sendRaw(carrier,envelope);queueForConfiguredBackends(envelope);}
    public void sendPrivateMessage(Player carrier,UUID senderId,String senderName,String targetName,UUID targetId,String message)throws IOException{ByteArrayOutputStream bytes=new ByteArrayOutputStream();DataOutputStream out=new DataOutputStream(bytes);out.writeInt(1);out.writeUTF("PM");out.writeUTF(senderId.toString());out.writeUTF(senderName);out.writeBoolean(targetId!=null);if(targetId!=null)out.writeUTF(targetId.toString());out.writeUTF(targetName);out.writeUTF(message);out.flush();forwardAll(carrier,bytes.toByteArray());}
    public void sendIgnoreChange(Player carrier,UUID viewer,UUID target,boolean ignored)throws IOException{ByteArrayOutputStream bytes=new ByteArrayOutputStream();DataOutputStream out=new DataOutputStream(bytes);out.writeInt(1);out.writeUTF("IGNORE");out.writeUTF(viewer.toString());out.writeUTF(target.toString());out.writeBoolean(ignored);out.flush();forwardAll(carrier,bytes.toByteArray());}
    private byte[] wrap(byte[] payload)throws IOException{UUID id=UUID.randomUUID();seenPackets.put(id,System.currentTimeMillis());ByteArrayOutputStream b=new ByteArrayOutputStream(payload.length+16);DataOutputStream out=new DataOutputStream(b);out.writeLong(id.getMostSignificantBits());out.writeLong(id.getLeastSignificantBits());out.write(payload);out.flush();return b.toByteArray();}
    private void sendRaw(Player carrier,byte[] payload)throws IOException{ByteArrayOutputStream outerBytes=new ByteArrayOutputStream();DataOutputStream outer=new DataOutputStream(outerBytes);outer.writeUTF("Forward");outer.writeUTF("ALL");outer.writeUTF(SUBCHANNEL);outer.writeShort(payload.length);outer.write(payload);outer.flush();carrier.sendPluginMessage(plugin,CHANNEL,outerBytes.toByteArray());}
    private void queueForConfiguredBackends(byte[] payload){if(!plugin.getStorage().isEnabled())return;String local=plugin.getPluginConfig().getString("network.server-name","server");for(String server:plugin.getPluginConfig().getStringList("network.servers"))if(!server.equalsIgnoreCase(local)&&!server.isBlank())plugin.getStorage().enqueueNetwork(server,payload);}
    @Override public void onPluginMessageReceived(String channel,Player source,byte[] data){if(!CHANNEL.equals(channel)||!plugin.getPluginConfig().getBoolean("network.enabled",true)||data==null)return;dispatch(data,source);}
    public boolean dispatch(byte[] data){return dispatch(data,null);}
    private boolean dispatch(byte[] data,Player source){try{DataInputStream outer=new DataInputStream(new ByteArrayInputStream(data));if(!"ThunderChat".equals(readUtfBounded(outer,64)))return true;int length=outer.readUnsignedShort();if(length<=0||length>outer.available())return true;byte[] envelope=outer.readNBytes(length);if(envelope.length<16)return true;DataInputStream wrapped=new DataInputStream(new ByteArrayInputStream(envelope));UUID packetId=new UUID(wrapped.readLong(),wrapped.readLong());if(seenPackets.putIfAbsent(packetId,System.currentTimeMillis())!=null)return true;byte[] payload=wrapped.readNBytes(wrapped.available());DataInputStream packet=new DataInputStream(new ByteArrayInputStream(payload));if(packet.readInt()!=1)return true;String kind=readUtfBounded(packet,32);if("MUTE".equals(kind)){plugin.getMuteManager().onNetworkPacket("BungeeCord",source,payload);return true;}if("IGNORE".equals(kind)){plugin.getIgnoreManager().onNetworkPacket(payload);return true;}if("PM".equals(kind)){UUID senderId=UUID.fromString(packet.readUTF());packet.readUTF();boolean hasTargetId=packet.readBoolean();UUID targetId=hasTargetId?UUID.fromString(packet.readUTF()):null;String targetName=packet.readUTF();if(plugin.getServer().getPlayer(senderId)!=null)return true;boolean handled=targetId!=null?plugin.getServer().getPlayer(targetId)!=null:plugin.getServer().getPlayerExact(targetName)!=null;plugin.getMessageManager().onNetworkPacket(payload);return handled;}if("CHAT".equals(kind)||"CLEAR".equals(kind)||"ALERT".equals(kind)){plugin.getGlobalChatManager().onNetworkPacket("BungeeCord",source,payload);return !Bukkit.getOnlinePlayers().isEmpty();}return true;}catch(IOException|RuntimeException e){plugin.getLogger().warning("Malformed ThunderChat network packet: "+e.getMessage());return true;}}
    private String readUtfBounded(DataInputStream input,int max)throws IOException{String value=input.readUTF();if(value.length()>max)throw new IOException("network string too long");return value;}
    public void drainQueuedPackets(){if(!plugin.getStorage().isEnabled())return;String server=plugin.getPluginConfig().getString("network.server-name","server");plugin.getStorage().drainNetwork(server,this::dispatch);}
    public void close(){plugin.getServer().getMessenger().unregisterIncomingPluginChannel(plugin,CHANNEL,this);plugin.getServer().getMessenger().unregisterOutgoingPluginChannel(plugin,CHANNEL);}
}
